x-be-env: &a1
  PORT: "1323"
  JWT_SECRET: S1Mpl3App4ng3lSuiC1d3
  NOTES_ENCRYPT_KEY: ganti-dengan-secret-minimal-16-karakter
  ALLOWED_FRONTEND_ORIGINS: http://localhost:3060,https://catatan-sihafid.joeichiro.my.id
  DB_DRIVER: mysql
  DB_HOST: host.docker.internal
  DB_PORT: "3306"
  DB_NAME: catatan
  DB_USER: root
  DB_PASSWORD: 
  DB_PARAMS: parseTime=true&charset=utf8mb4&loc=Local 
  GOOGLE_CLIENT_ID: 194218724970-870jicr294njjlmg05e9is2n65sapolj.apps.googleusercontent.com
  GEMINI_API_KEY: AIzaSyDoon-ULF2na3b-Fdppl3cslQ5SLDZlh4s 
x-fe-build-env: &a2
  PORT: "4321"
  # PUBLIC_API_BE_URL: https://rxmvmsat21lukf.joeichiro.my.id
  PUBLIC_API_BE_URL: /api
  PUBLIC_GOOGLE_CLIENT_ID: 194218724970-870jicr294njjlmg05e9is2n65sapolj.apps.googleusercontent.com
services:
  be:
    container_name: be
    build:
      context: ./be
      dockerfile: Dockerfile
    environment:
      <<: *a1
    expose:
      - "1323"
    restart: unless-stopped
  fe:
    container_name: fe
    build:
      context: ./fe
      dockerfile: Dockerfile
      args:
        <<: *a2
    environment:
      PORT: "4321"
      <<: *a2
    expose:
      - "4321"
    depends_on:
      - be
    restart: unless-stopped 
  nginx:
    container_name: nginx
    image: nginx:1.27-alpine
    depends_on:
      - fe
      - be 
    ports:
      - 3060:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
networks: {}
